# Generated by Django 6.0 on 2026-01-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img_type',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
