# Generated by Django 6.0.1 on 2026-02-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='type',
            field=models.CharField(choices=[('anime', 'Anime'), ('nature', 'Nature'), ('mountain', 'Mountain'), ('games', 'Games')], default='nature', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='device',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10),
        ),
    ]
